apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: movie-app
        image: mohdayazz/multibranch-flask-app:b14faae
        ports:
        - containerPort: 5000
